#服务配置
server:
  port: 8080

eureka:
  client:
    service-url:
      # EurekaServer地址
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: consumer-service


hystrix:
  command:
#   设置全局默认降级时间
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 3000
#   指定服务
    user-service:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 3000
